// <auto-generated />
using System;
using ClassroomManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassroomManagement.Api.Migrations
{
    [DbContext(typeof(ClassroomManagementDbContext))]
    [Migration("20260206134724_Initial Creation.")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassroomManagement.Api.Models.ClassSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("LabroomId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("CourseId");

                    b.HasIndex("LabroomId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ClassSchedules");
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 204
                        },
                        new
                        {
                            Id = 205
                        },
                        new
                        {
                            Id = 304
                        },
                        new
                        {
                            Id = 305
                        },
                        new
                        {
                            Id = 306
                        },
                        new
                        {
                            Id = 308
                        },
                        new
                        {
                            Id = 309
                        },
                        new
                        {
                            Id = 310
                        },
                        new
                        {
                            Id = 311
                        },
                        new
                        {
                            Id = 407
                        },
                        new
                        {
                            Id = 408
                        });
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Credit")
                        .HasColumnType("real");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Domains.Labroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Labrooms");

                    b.HasData(
                        new
                        {
                            Id = 202,
                            Name = "EEE"
                        },
                        new
                        {
                            Id = 210,
                            Name = "CSE"
                        },
                        new
                        {
                            Id = 302,
                            Name = "CSE"
                        },
                        new
                        {
                            Id = 307,
                            Name = "CSE"
                        },
                        new
                        {
                            Id = 311,
                            Name = "CSE"
                        },
                        new
                        {
                            Id = 402,
                            Name = "CSE, CAD"
                        },
                        new
                        {
                            Id = 411,
                            Name = "CSE"
                        },
                        new
                        {
                            Id = 1001,
                            Name = "AC Circuit Lab"
                        },
                        new
                        {
                            Id = 1002,
                            Name = "DC Circuit Lab"
                        },
                        new
                        {
                            Id = 1003,
                            Name = "AC Circuit Lab"
                        },
                        new
                        {
                            Id = 1004,
                            Name = "DWM Seminar Hall"
                        },
                        new
                        {
                            Id = 1005,
                            Name = "Electronics Lab"
                        },
                        new
                        {
                            Id = 1006,
                            Name = "Physics Lab"
                        });
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Domains.LevelTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.ToTable("LevelTerms");
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Domains.Sessional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Credit")
                        .HasColumnType("real");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Sessionals");
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("LabroomSessional", b =>
                {
                    b.Property<int>("AllowedSessionalsId")
                        .HasColumnType("int");

                    b.Property<int>("LabroomsId")
                        .HasColumnType("int");

                    b.HasKey("AllowedSessionalsId", "LabroomsId");

                    b.HasIndex("LabroomsId");

                    b.ToTable("LabroomSessional");
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.ClassSchedule", b =>
                {
                    b.HasOne("ClassroomManagement.Api.Models.Classroom", "Classroom")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomManagement.Api.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomManagement.Api.Models.Domains.Labroom", "Labroom")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("LabroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomManagement.Api.Models.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Course");

                    b.Navigation("Labroom");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Course", b =>
                {
                    b.HasOne("ClassroomManagement.Api.Models.Teacher", "Teacher")
                        .WithMany("AssignedCourses")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Domains.LevelTerm", b =>
                {
                    b.HasOne("ClassroomManagement.Api.Models.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Domains.Sessional", b =>
                {
                    b.HasOne("ClassroomManagement.Api.Models.Teacher", "Teacher")
                        .WithMany("AssignedSessionals")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LabroomSessional", b =>
                {
                    b.HasOne("ClassroomManagement.Api.Models.Domains.Sessional", null)
                        .WithMany()
                        .HasForeignKey("AllowedSessionalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomManagement.Api.Models.Domains.Labroom", null)
                        .WithMany()
                        .HasForeignKey("LabroomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Classroom", b =>
                {
                    b.Navigation("ClassSchedules");
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Domains.Labroom", b =>
                {
                    b.Navigation("ClassSchedules");
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Teacher", b =>
                {
                    b.Navigation("AssignedCourses");

                    b.Navigation("AssignedSessionals");

                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
