// <auto-generated />
using System;
using ClassroomManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassroomManagement.Api.Migrations
{
    [DbContext(typeof(ClassroomManagementDbContext))]
    [Migration("20260212161957_Updated the schedules for 4-II.")]
    partial class Updatedtheschedulesfor4II
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassroomManagement.Api.Models.ClassSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int?>("LabroomId")
                        .HasColumnType("int");

                    b.Property<int?>("SessionalId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("CourseId");

                    b.HasIndex("LabroomId");

                    b.HasIndex("SessionalId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ClassSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day = 0,
                            EndTime = new TimeOnly(8, 50, 0),
                            LabroomId = 307,
                            SessionalId = 31,
                            StartTime = new TimeOnly(8, 0, 0),
                            TeacherId = 31
                        },
                        new
                        {
                            Id = 2,
                            ClassroomId = 407,
                            CourseId = 33,
                            Day = 1,
                            EndTime = new TimeOnly(10, 50, 0),
                            StartTime = new TimeOnly(10, 0, 0),
                            TeacherId = 39
                        },
                        new
                        {
                            Id = 3,
                            ClassroomId = 407,
                            CourseId = 39,
                            Day = 1,
                            EndTime = new TimeOnly(12, 20, 0),
                            StartTime = new TimeOnly(11, 30, 0),
                            TeacherId = 31
                        },
                        new
                        {
                            Id = 4,
                            ClassroomId = 310,
                            CourseId = 41,
                            Day = 1,
                            EndTime = new TimeOnly(13, 20, 0),
                            StartTime = new TimeOnly(12, 30, 0),
                            TeacherId = 38
                        },
                        new
                        {
                            Id = 5,
                            ClassroomId = 407,
                            CourseId = 41,
                            Day = 2,
                            EndTime = new TimeOnly(8, 50, 0),
                            StartTime = new TimeOnly(8, 0, 0),
                            TeacherId = 38
                        },
                        new
                        {
                            Id = 6,
                            ClassroomId = 407,
                            CourseId = 39,
                            Day = 2,
                            EndTime = new TimeOnly(9, 50, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            TeacherId = 31
                        },
                        new
                        {
                            Id = 7,
                            ClassroomId = 407,
                            CourseId = 40,
                            Day = 2,
                            EndTime = new TimeOnly(10, 50, 0),
                            StartTime = new TimeOnly(10, 0, 0),
                            TeacherId = 33
                        },
                        new
                        {
                            Id = 8,
                            ClassroomId = 407,
                            CourseId = 33,
                            Day = 2,
                            EndTime = new TimeOnly(12, 20, 0),
                            StartTime = new TimeOnly(11, 30, 0),
                            TeacherId = 39
                        },
                        new
                        {
                            Id = 9,
                            ClassroomId = 407,
                            CourseId = 42,
                            Day = 3,
                            EndTime = new TimeOnly(12, 20, 0),
                            StartTime = new TimeOnly(11, 30, 0),
                            TeacherId = 40
                        },
                        new
                        {
                            Id = 10,
                            ClassroomId = 407,
                            CourseId = 40,
                            Day = 3,
                            EndTime = new TimeOnly(13, 20, 0),
                            StartTime = new TimeOnly(12, 30, 0),
                            TeacherId = 33
                        },
                        new
                        {
                            Id = 11,
                            ClassroomId = 407,
                            CourseId = 33,
                            Day = 3,
                            EndTime = new TimeOnly(14, 20, 0),
                            StartTime = new TimeOnly(13, 30, 0),
                            TeacherId = 39
                        },
                        new
                        {
                            Id = 12,
                            ClassroomId = 407,
                            CourseId = 40,
                            Day = 4,
                            EndTime = new TimeOnly(8, 50, 0),
                            StartTime = new TimeOnly(8, 0, 0),
                            TeacherId = 33
                        },
                        new
                        {
                            Id = 13,
                            ClassroomId = 407,
                            CourseId = 39,
                            Day = 4,
                            EndTime = new TimeOnly(9, 50, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            TeacherId = 31
                        },
                        new
                        {
                            Id = 14,
                            ClassroomId = 407,
                            CourseId = 42,
                            Day = 4,
                            EndTime = new TimeOnly(10, 50, 0),
                            StartTime = new TimeOnly(10, 0, 0),
                            TeacherId = 40
                        },
                        new
                        {
                            Id = 15,
                            ClassroomId = 305,
                            CourseId = 43,
                            Day = 4,
                            EndTime = new TimeOnly(12, 20, 0),
                            StartTime = new TimeOnly(11, 30, 0),
                            TeacherId = 41
                        });
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 204
                        },
                        new
                        {
                            Id = 205
                        },
                        new
                        {
                            Id = 304
                        },
                        new
                        {
                            Id = 305
                        },
                        new
                        {
                            Id = 306
                        },
                        new
                        {
                            Id = 308
                        },
                        new
                        {
                            Id = 309
                        },
                        new
                        {
                            Id = 310
                        },
                        new
                        {
                            Id = 311
                        },
                        new
                        {
                            Id = 407
                        },
                        new
                        {
                            Id = 408
                        },
                        new
                        {
                            Id = 1001
                        });
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Credit")
                        .HasColumnType("real");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseCode = "EEE 1163",
                            Credit = 3f,
                            Level = 1,
                            Name = "Introduction to Electrical Engineering",
                            TeacherId = 1,
                            Term = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseCode = "CSE 1101",
                            Credit = 3f,
                            Level = 1,
                            Name = "Structured Programming Language",
                            TeacherId = 2,
                            Term = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseCode = "PHY 1131",
                            Credit = 3f,
                            Level = 1,
                            Name = "Physics",
                            TeacherId = 3,
                            Term = 1
                        },
                        new
                        {
                            Id = 4,
                            CourseCode = "ENG 1127",
                            Credit = 3f,
                            Level = 1,
                            Name = "English",
                            TeacherId = 5,
                            Term = 1
                        },
                        new
                        {
                            Id = 5,
                            CourseCode = "MATH 1141",
                            Credit = 3f,
                            Level = 1,
                            Name = "Differential Calculus, Integral Calculus, and Coordinate Geometry",
                            Term = 1
                        },
                        new
                        {
                            Id = 6,
                            CourseCode = "CSE 1203",
                            Credit = 3f,
                            Level = 1,
                            Name = "Object Oriented Programming Language I",
                            TeacherId = 8,
                            Term = 2
                        },
                        new
                        {
                            Id = 7,
                            CourseCode = "EEE 1269",
                            Credit = 3f,
                            Level = 1,
                            Name = "Electronic Circuits",
                            TeacherId = 10,
                            Term = 2
                        },
                        new
                        {
                            Id = 8,
                            CourseCode = "MATH 1243",
                            Credit = 3f,
                            Level = 1,
                            Name = "Ordinary Differential Equations and Partial Differential Equations",
                            TeacherId = 11,
                            Term = 2
                        },
                        new
                        {
                            Id = 9,
                            CourseCode = "CSE 1201",
                            Credit = 3f,
                            Level = 1,
                            Name = "Discrete Mathematics",
                            TeacherId = 14,
                            Term = 2
                        },
                        new
                        {
                            Id = 10,
                            CourseCode = "HUM 1221",
                            Credit = 2f,
                            Level = 1,
                            Name = "Bengali Language and Literature",
                            TeacherId = 45,
                            Term = 2
                        },
                        new
                        {
                            Id = 11,
                            CourseCode = "CSE 2101",
                            Credit = 3f,
                            Level = 2,
                            Name = "Digital Logic Design",
                            TeacherId = 16,
                            Term = 1
                        },
                        new
                        {
                            Id = 12,
                            CourseCode = "CHEM 2133",
                            Credit = 3f,
                            Level = 2,
                            Name = "Chemistry",
                            TeacherId = 17,
                            Term = 1
                        },
                        new
                        {
                            Id = 13,
                            CourseCode = "MATH 2145",
                            Credit = 3f,
                            Level = 2,
                            Name = "Vector Calculus, Linear Algebra and Complex Variable",
                            TeacherId = 18,
                            Term = 1
                        },
                        new
                        {
                            Id = 14,
                            CourseCode = "CSE 2103",
                            Credit = 3f,
                            Level = 2,
                            Name = "Data Structures and Algorithm I",
                            TeacherId = 19,
                            Term = 1
                        },
                        new
                        {
                            Id = 15,
                            CourseCode = "CSE 2105",
                            Credit = 3f,
                            Level = 2,
                            Name = "Applied Statistics for Computer Science",
                            TeacherId = 20,
                            Term = 1
                        },
                        new
                        {
                            Id = 16,
                            CourseCode = "CSE 2201",
                            Credit = 3f,
                            Level = 2,
                            Name = "Data Structures and Algorithm II",
                            TeacherId = 21,
                            Term = 2
                        },
                        new
                        {
                            Id = 17,
                            CourseCode = "MATH 2247",
                            Credit = 3f,
                            Level = 2,
                            Name = "Laplace Transformation and Fourier Analysis",
                            TeacherId = 22,
                            Term = 2
                        },
                        new
                        {
                            Id = 18,
                            CourseCode = "CSE 2203",
                            Credit = 3f,
                            Level = 2,
                            Name = "Theory of Computation",
                            TeacherId = 23,
                            Term = 2
                        },
                        new
                        {
                            Id = 19,
                            CourseCode = "EEE 2269",
                            Credit = 3f,
                            Level = 2,
                            Name = "Electrical Drives and Instrumentation",
                            TeacherId = 26,
                            Term = 2
                        },
                        new
                        {
                            Id = 20,
                            CourseCode = "CSE 2205",
                            Credit = 3f,
                            Level = 2,
                            Name = "Database Management Systems",
                            TeacherId = 24,
                            Term = 2
                        },
                        new
                        {
                            Id = 21,
                            CourseCode = "HUM 2221",
                            Credit = 2f,
                            Level = 2,
                            Name = "History of the Emergence of Bangladesh",
                            TeacherId = 46,
                            Term = 2
                        },
                        new
                        {
                            Id = 22,
                            CourseCode = "CSE 3109",
                            Credit = 3f,
                            Level = 3,
                            Name = "Compiler",
                            TeacherId = 28,
                            Term = 1
                        },
                        new
                        {
                            Id = 23,
                            CourseCode = "CSE 3103",
                            Credit = 3f,
                            Level = 3,
                            Name = "Microprocessors, Microcontrollers and Embedded Systems",
                            TeacherId = 29,
                            Term = 1
                        },
                        new
                        {
                            Id = 24,
                            CourseCode = "CSE 3107",
                            Credit = 3f,
                            Level = 3,
                            Name = "Data Communication",
                            TeacherId = 4,
                            Term = 1
                        },
                        new
                        {
                            Id = 25,
                            CourseCode = "CSE 3101",
                            Credit = 3f,
                            Level = 3,
                            Name = "Software Engineering",
                            TeacherId = 12,
                            Term = 1
                        },
                        new
                        {
                            Id = 26,
                            CourseCode = "ME 3181",
                            Credit = 3f,
                            Level = 3,
                            Name = "Basic Mechanical Engineering",
                            TeacherId = 47,
                            Term = 1
                        },
                        new
                        {
                            Id = 27,
                            CourseCode = "CSE 3105",
                            Credit = 3f,
                            Level = 3,
                            Name = "Computer Architecture",
                            TeacherId = 9,
                            Term = 1
                        },
                        new
                        {
                            Id = 28,
                            CourseCode = "CSE 3201",
                            Credit = 3f,
                            Level = 3,
                            Name = "Artificial Intelligence",
                            TeacherId = 32,
                            Term = 2
                        },
                        new
                        {
                            Id = 29,
                            CourseCode = "CSE 3203",
                            Credit = 3f,
                            Level = 3,
                            Name = "Operating System",
                            TeacherId = 30,
                            Term = 2
                        },
                        new
                        {
                            Id = 30,
                            CourseCode = "CSE 3207",
                            Credit = 3f,
                            Level = 3,
                            Name = "Mathematical Analysis for Computer Science",
                            TeacherId = 25,
                            Term = 2
                        },
                        new
                        {
                            Id = 31,
                            CourseCode = "CSE 3205",
                            Credit = 3f,
                            Level = 3,
                            Name = "Computer Networks",
                            TeacherId = 31,
                            Term = 2
                        },
                        new
                        {
                            Id = 32,
                            CourseCode = "CSE 3209",
                            Credit = 3f,
                            Level = 3,
                            Name = "Information System Design",
                            TeacherId = 13,
                            Term = 2
                        },
                        new
                        {
                            Id = 33,
                            CourseCode = "IPE 4217",
                            Credit = 2f,
                            Level = 3,
                            Name = "Industrial Management",
                            TeacherId = 39,
                            Term = 2
                        },
                        new
                        {
                            Id = 34,
                            CourseCode = "CSE 4139",
                            Credit = 3f,
                            Level = 4,
                            Name = "Machine Learning",
                            TeacherId = 33,
                            Term = 1
                        },
                        new
                        {
                            Id = 35,
                            CourseCode = "CSE 4103",
                            Credit = 3f,
                            Level = 4,
                            Name = "Computer Graphics",
                            TeacherId = 34,
                            Term = 1
                        },
                        new
                        {
                            Id = 36,
                            CourseCode = "HUM 4123",
                            Credit = 3f,
                            Level = 4,
                            Name = "Engineering Economics",
                            TeacherId = 36,
                            Term = 1
                        },
                        new
                        {
                            Id = 37,
                            CourseCode = "CSE 4141",
                            Credit = 3f,
                            Level = 4,
                            Name = "Object Oriented Software Engineering",
                            TeacherId = 8,
                            Term = 1
                        },
                        new
                        {
                            Id = 38,
                            CourseCode = "CSE 4101",
                            Credit = 3f,
                            Level = 4,
                            Name = "Computer Security",
                            TeacherId = 35,
                            Term = 1
                        },
                        new
                        {
                            Id = 39,
                            CourseCode = "CSE 4251",
                            Credit = 2f,
                            Level = 4,
                            Name = "Data Warehousing and Data Mining",
                            TeacherId = 31,
                            Term = 2
                        },
                        new
                        {
                            Id = 40,
                            CourseCode = "CSE 4245",
                            Credit = 2f,
                            Level = 4,
                            Name = "Digital Image Processing",
                            TeacherId = 33,
                            Term = 2
                        },
                        new
                        {
                            Id = 41,
                            CourseCode = "CSE 4215",
                            Credit = 2f,
                            Level = 4,
                            Name = "Professional Issues and Ethics in Computer Science",
                            TeacherId = 38,
                            Term = 2
                        },
                        new
                        {
                            Id = 42,
                            CourseCode = "HUM 4273",
                            Credit = 2f,
                            Level = 4,
                            Name = "Financial, Cost and Managerial Accounting",
                            TeacherId = 40,
                            Term = 2
                        },
                        new
                        {
                            Id = 43,
                            CourseCode = "CSE 4249",
                            Credit = 2f,
                            Level = 4,
                            Name = "VLSI Design",
                            TeacherId = 41,
                            Term = 2
                        });
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Domains.Labroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Labrooms");

                    b.HasData(
                        new
                        {
                            Id = 202,
                            Name = "EEE"
                        },
                        new
                        {
                            Id = 210,
                            Name = "CSE"
                        },
                        new
                        {
                            Id = 302,
                            Name = "CSE"
                        },
                        new
                        {
                            Id = 307,
                            Name = "CSE"
                        },
                        new
                        {
                            Id = 311,
                            Name = "CSE"
                        },
                        new
                        {
                            Id = 402,
                            Name = "CSE, CAD"
                        },
                        new
                        {
                            Id = 411,
                            Name = "CSE"
                        },
                        new
                        {
                            Id = 1001,
                            Name = "AC Circuit Lab"
                        },
                        new
                        {
                            Id = 1002,
                            Name = "DC Circuit Lab"
                        },
                        new
                        {
                            Id = 1003,
                            Name = "AC Circuit Lab"
                        },
                        new
                        {
                            Id = 1004,
                            Name = "Electronics Lab"
                        },
                        new
                        {
                            Id = 1005,
                            Name = "Physics Lab"
                        });
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Domains.LevelTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId")
                        .IsUnique();

                    b.ToTable("LevelTerms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassroomId = 408,
                            Level = 1,
                            Term = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassroomId = 308,
                            Level = 1,
                            Term = 2
                        },
                        new
                        {
                            Id = 3,
                            ClassroomId = 305,
                            Level = 2,
                            Term = 1
                        },
                        new
                        {
                            Id = 4,
                            ClassroomId = 309,
                            Level = 2,
                            Term = 2
                        },
                        new
                        {
                            Id = 5,
                            ClassroomId = 304,
                            Level = 3,
                            Term = 1
                        },
                        new
                        {
                            Id = 6,
                            ClassroomId = 204,
                            Level = 3,
                            Term = 2
                        },
                        new
                        {
                            Id = 7,
                            ClassroomId = 306,
                            Level = 4,
                            Term = 1
                        },
                        new
                        {
                            Id = 8,
                            ClassroomId = 407,
                            Level = 4,
                            Term = 2
                        });
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Domains.Sessional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Credit")
                        .HasColumnType("real");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Sessionals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credit = 1.5f,
                            Level = 1,
                            Name = "Introduction to Computer System Sessional",
                            SessionalCode = "CSE 1100",
                            TeacherId = 9,
                            Term = 1
                        },
                        new
                        {
                            Id = 2,
                            Credit = 1.5f,
                            Level = 1,
                            Name = "Structured Programming Language Sessional",
                            SessionalCode = "CSE 1102",
                            TeacherId = 2,
                            Term = 1
                        },
                        new
                        {
                            Id = 3,
                            Credit = 1.5f,
                            Level = 1,
                            Name = "Introduction to Electrical Engineering Sessional",
                            SessionalCode = "EEE 1164",
                            TeacherId = 7,
                            Term = 1
                        },
                        new
                        {
                            Id = 4,
                            Credit = 0.75f,
                            Level = 1,
                            Name = "Physics Sessional",
                            SessionalCode = "PHY 1132",
                            TeacherId = 3,
                            Term = 1
                        },
                        new
                        {
                            Id = 5,
                            Credit = 1.5f,
                            Level = 1,
                            Name = "Object Oriented Programming Language I Sessional",
                            SessionalCode = "CSE 1204",
                            TeacherId = 8,
                            Term = 2
                        },
                        new
                        {
                            Id = 6,
                            Credit = 1.5f,
                            Level = 1,
                            Name = "Numerical Methods Sessional",
                            SessionalCode = "CSE 1208",
                            TeacherId = 12,
                            Term = 2
                        },
                        new
                        {
                            Id = 7,
                            Credit = 0.75f,
                            Level = 1,
                            Name = "Electronic Circuits Sessional",
                            SessionalCode = "EEE 1270",
                            TeacherId = 26,
                            Term = 2
                        },
                        new
                        {
                            Id = 8,
                            Credit = 0.75f,
                            Level = 1,
                            Name = "Engineering Drawing and CAD Sessional",
                            SessionalCode = "CE 1250",
                            TeacherId = 43,
                            Term = 2
                        },
                        new
                        {
                            Id = 9,
                            Credit = 0.75f,
                            Level = 1,
                            Name = "Developing English Skill Sessional",
                            SessionalCode = "ENG 1228",
                            TeacherId = 44,
                            Term = 2
                        },
                        new
                        {
                            Id = 10,
                            Credit = 1.5f,
                            Level = 2,
                            Name = "Digital Logic Design Sessional",
                            SessionalCode = "CSE 2102",
                            TeacherId = 37,
                            Term = 1
                        },
                        new
                        {
                            Id = 11,
                            Credit = 1.5f,
                            Level = 2,
                            Name = "Data Structures and Algorithm I Sessional",
                            SessionalCode = "CSE 2104",
                            TeacherId = 19,
                            Term = 1
                        },
                        new
                        {
                            Id = 12,
                            Credit = 1.5f,
                            Level = 2,
                            Name = "Object Oriented Programming Language II Sessional",
                            SessionalCode = "CSE 2108",
                            TeacherId = 34,
                            Term = 1
                        },
                        new
                        {
                            Id = 13,
                            Credit = 0.75f,
                            Level = 2,
                            Name = "Software Development Project I",
                            SessionalCode = "CSE 2100",
                            TeacherId = 4,
                            Term = 1
                        },
                        new
                        {
                            Id = 14,
                            Credit = 1.5f,
                            Level = 2,
                            Name = "Data Structures and Algorithm II Sessional",
                            SessionalCode = "CSE 2202",
                            TeacherId = 20,
                            Term = 2
                        },
                        new
                        {
                            Id = 15,
                            Credit = 1.5f,
                            Level = 2,
                            Name = "Database Management Systems Sessional",
                            SessionalCode = "CSE 2206",
                            TeacherId = 24,
                            Term = 2
                        },
                        new
                        {
                            Id = 16,
                            Credit = 0.75f,
                            Level = 2,
                            Name = "Electrical Drives and Instrumentation Sessional",
                            SessionalCode = "EEE 2270",
                            TeacherId = 27,
                            Term = 2
                        },
                        new
                        {
                            Id = 17,
                            Credit = 0.75f,
                            Level = 3,
                            Name = "Software Engineering Sessional",
                            SessionalCode = "CSE 3102",
                            TeacherId = 12,
                            Term = 1
                        },
                        new
                        {
                            Id = 18,
                            Credit = 0.75f,
                            Level = 3,
                            Name = "Microprocessors, Microcontrollers and Embedded Systems Sessional",
                            SessionalCode = "CSE 3104",
                            TeacherId = 29,
                            Term = 1
                        },
                        new
                        {
                            Id = 19,
                            Credit = 0.75f,
                            Level = 3,
                            Name = "Compiler Sessional",
                            SessionalCode = "CSE 3110",
                            TeacherId = 28,
                            Term = 1
                        },
                        new
                        {
                            Id = 20,
                            Credit = 0.75f,
                            Level = 3,
                            Name = "Software Development Project II",
                            SessionalCode = "CSE 3100",
                            TeacherId = 4,
                            Term = 1
                        },
                        new
                        {
                            Id = 21,
                            Credit = 0.75f,
                            Level = 3,
                            Name = "Artificial Intelligence Sessional",
                            SessionalCode = "CSE 3202",
                            TeacherId = 32,
                            Term = 2
                        },
                        new
                        {
                            Id = 22,
                            Credit = 1.5f,
                            Level = 3,
                            Name = "Operating System Sessional",
                            SessionalCode = "CSE 3204",
                            TeacherId = 37,
                            Term = 2
                        },
                        new
                        {
                            Id = 23,
                            Credit = 1.5f,
                            Level = 3,
                            Name = "Computer Networks Sessional",
                            SessionalCode = "CSE 3206",
                            TeacherId = 28,
                            Term = 2
                        },
                        new
                        {
                            Id = 24,
                            Credit = 0.75f,
                            Level = 3,
                            Name = "Information System Design Sessional",
                            SessionalCode = "CSE 3210",
                            TeacherId = 32,
                            Term = 2
                        },
                        new
                        {
                            Id = 25,
                            Credit = 1.5f,
                            Level = 3,
                            Name = "Web Engineering Project",
                            SessionalCode = "CSE 3200",
                            TeacherId = 23,
                            Term = 2
                        },
                        new
                        {
                            Id = 26,
                            Credit = 0.75f,
                            Level = 4,
                            Name = "Computer Security Sessional",
                            SessionalCode = "CSE 4102",
                            TeacherId = 35,
                            Term = 1
                        },
                        new
                        {
                            Id = 27,
                            Credit = 0.75f,
                            Level = 4,
                            Name = "Computer Graphics Sessional",
                            SessionalCode = "CSE 4104",
                            TeacherId = 29,
                            Term = 1
                        },
                        new
                        {
                            Id = 28,
                            Credit = 0.75f,
                            Level = 4,
                            Name = "Machine Learning Sessional",
                            SessionalCode = "CSE 4140",
                            TeacherId = 16,
                            Term = 1
                        },
                        new
                        {
                            Id = 29,
                            Credit = 0.75f,
                            Level = 4,
                            Name = "Object Oriented Software Engineering Sessional",
                            SessionalCode = "CSE 4142",
                            TeacherId = 8,
                            Term = 1
                        },
                        new
                        {
                            Id = 30,
                            Credit = 0.75f,
                            Level = 4,
                            Name = "Digital Image Processing Sessional",
                            SessionalCode = "CSE 4246",
                            TeacherId = 33,
                            Term = 2
                        },
                        new
                        {
                            Id = 31,
                            Credit = 0.75f,
                            Level = 4,
                            Name = "Data Warehousing and Data Mining Sessional",
                            SessionalCode = "CSE 4252",
                            TeacherId = 31,
                            Term = 2
                        });
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "TQA",
                            Designation = "Lecturer",
                            Name = "TQA"
                        },
                        new
                        {
                            Id = 2,
                            Code = "NHC",
                            Designation = "Lecturer",
                            Name = "NHC"
                        },
                        new
                        {
                            Id = 3,
                            Code = "PHY",
                            Designation = "Assistant Professor",
                            Name = "PHY"
                        },
                        new
                        {
                            Id = 4,
                            Code = "MAM",
                            Designation = "Assistant Professor",
                            Name = "MAM"
                        },
                        new
                        {
                            Id = 5,
                            Code = "ENG1",
                            Designation = "Lecturer",
                            Name = "ENG1"
                        },
                        new
                        {
                            Id = 6,
                            Code = "EEE1",
                            Designation = "Lecturer",
                            Name = "EEE1"
                        },
                        new
                        {
                            Id = 7,
                            Code = "MA",
                            Designation = "Lecturer",
                            Name = "MA"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AH",
                            Designation = "Assistant Professor",
                            Name = "AH"
                        },
                        new
                        {
                            Id = 9,
                            Code = "MH",
                            Designation = "Lecturer",
                            Name = "MH"
                        },
                        new
                        {
                            Id = 10,
                            Code = "EMH",
                            Designation = "Lecturer",
                            Name = "EMH"
                        },
                        new
                        {
                            Id = 11,
                            Code = "MATH2",
                            Designation = "Assistant Professor",
                            Name = "MATH2"
                        },
                        new
                        {
                            Id = 12,
                            Code = "SG",
                            Designation = "Lecturer",
                            Name = "SG"
                        },
                        new
                        {
                            Id = 13,
                            Code = "MSZ",
                            Designation = "Lecturer",
                            Name = "MSZ"
                        },
                        new
                        {
                            Id = 14,
                            Code = "AHS",
                            Designation = "Lecturer",
                            Name = "AHS"
                        },
                        new
                        {
                            Id = 15,
                            Code = "ASM",
                            Designation = "Lecturer",
                            Name = "ASM"
                        },
                        new
                        {
                            Id = 16,
                            Code = "MSA",
                            Designation = "Assistant Professor",
                            Name = "MSA"
                        },
                        new
                        {
                            Id = 17,
                            Code = "CHEM",
                            Designation = "Assistant Professor",
                            Name = "CHEM"
                        },
                        new
                        {
                            Id = 18,
                            Code = "MATH3",
                            Designation = "Professor",
                            Name = "MATH3"
                        },
                        new
                        {
                            Id = 19,
                            Code = "MZH",
                            Designation = "Assistant Professor",
                            Name = "MZH"
                        },
                        new
                        {
                            Id = 20,
                            Code = "MO",
                            Designation = "Lecturer",
                            Name = "MO"
                        },
                        new
                        {
                            Id = 21,
                            Code = "RR",
                            Designation = "Assistant Professor",
                            Name = "RR"
                        },
                        new
                        {
                            Id = 22,
                            Code = "MATH4",
                            Designation = "Professor",
                            Name = "MATH4"
                        },
                        new
                        {
                            Id = 23,
                            Code = "ST",
                            Designation = "Assistant Professor",
                            Name = "ST"
                        },
                        new
                        {
                            Id = 24,
                            Code = "AKZ",
                            Designation = "Lecturer",
                            Name = "AKZ"
                        },
                        new
                        {
                            Id = 25,
                            Code = "GR",
                            Designation = "Assistant Professor",
                            Name = "GR"
                        },
                        new
                        {
                            Id = 26,
                            Code = "EAS",
                            Designation = "Lecturer",
                            Name = "EAS"
                        },
                        new
                        {
                            Id = 27,
                            Code = "EEE2",
                            Designation = "Lecturer",
                            Name = "EEE2"
                        },
                        new
                        {
                            Id = 28,
                            Code = "MI",
                            Designation = "Assistant Professor",
                            Name = "MI"
                        },
                        new
                        {
                            Id = 29,
                            Code = "TMM",
                            Designation = "Lecturer",
                            Name = "TMM"
                        },
                        new
                        {
                            Id = 30,
                            Code = "NAO",
                            Designation = "Lecturer",
                            Name = "NAO"
                        },
                        new
                        {
                            Id = 31,
                            Code = "NR",
                            Designation = "Assistant Professor",
                            Name = "NR"
                        },
                        new
                        {
                            Id = 32,
                            Code = "AS",
                            Designation = "Assistant Professor",
                            Name = "AS"
                        },
                        new
                        {
                            Id = 33,
                            Code = "JA",
                            Designation = "Lecturer",
                            Name = "JA"
                        },
                        new
                        {
                            Id = 34,
                            Code = "AA",
                            Designation = "Lecturer",
                            Name = "AA"
                        },
                        new
                        {
                            Id = 35,
                            Code = "AZ",
                            Designation = "Lecturer",
                            Name = "AZ"
                        },
                        new
                        {
                            Id = 36,
                            Code = "BBA",
                            Designation = "Lecturer",
                            Name = "BBA"
                        },
                        new
                        {
                            Id = 37,
                            Code = "SA",
                            Designation = "Lecturer",
                            Name = "SA"
                        },
                        new
                        {
                            Id = 38,
                            Code = "NF1",
                            Designation = "Lecturer",
                            Name = "NF1"
                        },
                        new
                        {
                            Id = 39,
                            Code = "IPE",
                            Designation = "Assistant Professor",
                            Name = "IPE"
                        },
                        new
                        {
                            Id = 40,
                            Code = "AIS",
                            Designation = "Lecturer",
                            Name = "AIS"
                        },
                        new
                        {
                            Id = 41,
                            Code = "RA",
                            Designation = "Lecturer",
                            Name = "RA"
                        },
                        new
                        {
                            Id = 42,
                            Code = "MAS",
                            Designation = "Lecturer",
                            Name = "MAS"
                        },
                        new
                        {
                            Id = 43,
                            Code = "PR",
                            Designation = "Lecturer",
                            Name = "PR"
                        },
                        new
                        {
                            Id = 44,
                            Code = "ENG2",
                            Designation = "Lecturer",
                            Name = "ENG2"
                        },
                        new
                        {
                            Id = 45,
                            Code = "HUM1",
                            Designation = "Lecturer",
                            Name = "HUM1"
                        },
                        new
                        {
                            Id = 46,
                            Code = "HUM2",
                            Designation = "Lecturer",
                            Name = "HUM2"
                        },
                        new
                        {
                            Id = 47,
                            Code = "ME",
                            Designation = "Assistant Professor",
                            Name = "ME"
                        },
                        new
                        {
                            Id = 48,
                            Code = "NHS",
                            Designation = "Lecturer",
                            Name = "NHS"
                        });
                });

            modelBuilder.Entity("LabroomSessional", b =>
                {
                    b.Property<int>("AllowedSessionalsId")
                        .HasColumnType("int");

                    b.Property<int>("LabroomsId")
                        .HasColumnType("int");

                    b.HasKey("AllowedSessionalsId", "LabroomsId");

                    b.HasIndex("LabroomsId");

                    b.ToTable("LabroomSessional");
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.ClassSchedule", b =>
                {
                    b.HasOne("ClassroomManagement.Api.Models.Classroom", "Classroom")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("ClassroomId");

                    b.HasOne("ClassroomManagement.Api.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("ClassroomManagement.Api.Models.Domains.Labroom", "Labroom")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("LabroomId");

                    b.HasOne("ClassroomManagement.Api.Models.Domains.Sessional", "Sessional")
                        .WithMany()
                        .HasForeignKey("SessionalId");

                    b.HasOne("ClassroomManagement.Api.Models.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Course");

                    b.Navigation("Labroom");

                    b.Navigation("Sessional");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Course", b =>
                {
                    b.HasOne("ClassroomManagement.Api.Models.Teacher", "Teacher")
                        .WithMany("AssignedCourses")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Domains.LevelTerm", b =>
                {
                    b.HasOne("ClassroomManagement.Api.Models.Classroom", "Classroom")
                        .WithOne("LevelTerm")
                        .HasForeignKey("ClassroomManagement.Api.Models.Domains.LevelTerm", "ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Domains.Sessional", b =>
                {
                    b.HasOne("ClassroomManagement.Api.Models.Teacher", "Teacher")
                        .WithMany("AssignedSessionals")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LabroomSessional", b =>
                {
                    b.HasOne("ClassroomManagement.Api.Models.Domains.Sessional", null)
                        .WithMany()
                        .HasForeignKey("AllowedSessionalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassroomManagement.Api.Models.Domains.Labroom", null)
                        .WithMany()
                        .HasForeignKey("LabroomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Classroom", b =>
                {
                    b.Navigation("ClassSchedules");

                    b.Navigation("LevelTerm");
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Domains.Labroom", b =>
                {
                    b.Navigation("ClassSchedules");
                });

            modelBuilder.Entity("ClassroomManagement.Api.Models.Teacher", b =>
                {
                    b.Navigation("AssignedCourses");

                    b.Navigation("AssignedSessionals");

                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
